[package]
name = "metro-m4-examples"
version = "0.1.0"
authors = ["Paul Sajna <sajattack@gmail.com>"]
edition = "2018"

[dev-dependencies]
metro_m4 = "0.5"
panic-halt = "0.2"
st7735-lcd = "0.7"
embedded-graphics = "0.6"
